name: Run Script

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Makefile
        run: |
          make

      - name: Execute Script
        run: |
          # تم تغيير اسم الملف هنا ليطابق udp_stress
          timeout 60 ./udp_stress 300 || true
